/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import clases.DestinoTuristico;
import gestion.SistemaAgencia;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
/**
 *
 * @author Phillipe
 */
public class MantenimientoDestinos extends javax.swing.JFrame {
    private SistemaAgencia sistema;
    private DefaultTableModel modelo;
    private JTable tbDestinos;
    private JTextField txtNombre, txtPais, txtCiudad, txtDescripcion, txtClima, txtIdioma, txtImagen;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MantenimientoDestinos.class.getName());

    /**
     * Creates new form MantenimientoDestinos
     */
    public MantenimientoDestinos(SistemaAgencia sistema) {
        this.sistema = sistema;
        setTitle("Gestión de Destinos Turísticos");
        setSize(750, 500);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLayout(new BorderLayout());

        JPanel pnlDatos = new JPanel(new GridLayout(4, 4, 10, 10));
        pnlDatos.setBorder(BorderFactory.createTitledBorder("Datos del Destino"));

        // Campos basados en la clase DestinoTuristico[cite: 11]
        pnlDatos.add(new JLabel("Nombre:")); txtNombre = new JTextField(); pnlDatos.add(txtNombre);
        pnlDatos.add(new JLabel("País:")); txtPais = new JTextField(); pnlDatos.add(txtPais);
        pnlDatos.add(new JLabel("Ciudad:")); txtCiudad = new JTextField(); pnlDatos.add(txtCiudad);
        pnlDatos.add(new JLabel("Descripción:")); txtDescripcion = new JTextField(); pnlDatos.add(txtDescripcion);
        pnlDatos.add(new JLabel("Clima:")); txtClima = new JTextField(); pnlDatos.add(txtClima);
        pnlDatos.add(new JLabel("Idioma:")); txtIdioma = new JTextField(); pnlDatos.add(txtIdioma);
        pnlDatos.add(new JLabel("Ruta Imagen:")); txtImagen = new JTextField(); pnlDatos.add(txtImagen);

        JPanel pnlBotones = new JPanel();
        JButton btnRegistrar = new JButton("Registrar Destino");
        pnlBotones.add(btnRegistrar);

        JPanel pnlTop = new JPanel(new BorderLayout());
        pnlTop.add(pnlDatos, BorderLayout.CENTER);
        pnlTop.add(pnlBotones, BorderLayout.SOUTH);
        add(pnlTop, BorderLayout.NORTH);

        modelo = new DefaultTableModel(new String[]{"Nombre", "País", "Ciudad", "Clima", "Idioma"}, 0);
        tbDestinos = new JTable(modelo);
        add(new JScrollPane(tbDestinos), BorderLayout.CENTER);

        btnRegistrar.addActionListener(e -> {
            DestinoTuristico d = new DestinoTuristico(
                txtNombre.getText(), txtPais.getText(), txtCiudad.getText(),
                txtDescripcion.getText(), txtClima.getText(), txtIdioma.getText(),
                txtImagen.getText()
            );

            // Nota: Debes crear registrarDestino() y getDestinos() en tu clase SistemaAgencia
            // de la misma forma que lo hicimos con Clientes y Empleados.
            /*
            if (sistema.registrarDestino(d)) {
                listar();
                JOptionPane.showMessageDialog(this, "Destino Registrado");
            }
            */
            JOptionPane.showMessageDialog(this, "Asegúrate de agregar el arreglo de Destinos en SistemaAgencia.java");
        });
    }
}
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MantenimientoDestinos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
